new python backend
osohq/gitclub pull request #18
Opened 2021-09-02 19:57 UTC by gw000

2021-09-09 15:59 UTC, dhatch commented
This backend also uses SQLAlchemy, so we might want to come up with a way to explain the difference between the two. I would expect users of `SQLAlchemy` to use the `flask-sqlalchemy` backend as an example. If someone doesn't use SQLAlchemy and uses another ORM, they might use this as an example of how to use the new data filtering API with their own ORM.

2021-09-09 15:59 UTC, dhatch commented
Also should add to the README.

2021-09-09 16:15 UTC, dhatch reviewed
Brief comments from reading this code a bit -- not a thorough review.

2021-09-09 16:15 UTC, dhatch commented on backends/flask/app/__init__.py
> +    Relation = import_module("polar.data_filtering", "oso").Relation
Curious why this is necessary. Could you just have a top level import? `from polar import data_filtering`?

2021-09-09 16:15 UTC, dhatch commented on backends/flask/app/__init__.py
> +        return go
We should use longer variable names here since we expect users to copy this. I put some suggestions below -- didn't test this snippet though. Also, is `fetcher` the name we decided on for these functions? I also thought we were planning on calling constraints filters based on https://www.notion.so/osohq/Fall-2021-Product-Naming-8ff17513d0934d9fbfa3ddfc9dcadb9c#2fe700d5e5dd41bfb22f3830cb1bceb3. Do we need to make updates throughout the code & docs still for this?


```suggestion
    def fetcher(model):
        def to_sqlalchemy_filter(constraint):
            if constraint.field is not None:
                field = getattr(model, constraint.field)
                value = constraint.value
            else:
                field = model.id
                value = constraint.value.id

            if constraint.kind == "Eq":
                return field == value
            elif constraint.kind == "In":
                return field.in_(value)
            else:
                raise OsoError(f"Unsupported constraint kind: {constraint.kind}")

        def build_query(constraints):
            pred = and_(*[to_sqlalchemy_filter(c) for c in constraints])
            return Session().query(model).filter(pred)

        return build_query
```

2021-09-09 16:16 UTC, dhatch commented on backends/flask/app/__init__.py
> +        return go
Comments may also be helpful here.

2021-09-09 16:23 UTC, dhatch commented on backends/flask/app/routes/orgs.py
> +    if not current_app.oso.is_allowed(g.current_user, "create", org):
Can we use `authorize` here instead?

2021-09-09 17:41 UTC, gw000 commented on backends/flask/app/routes/orgs.py
> +    if not current_app.oso.is_allowed(g.current_user, "create", org):
👍

2021-09-09 18:03 UTC, gw000 commented on backends/flask/app/__init__.py
> +        return go
👍 added

2021-09-09 18:07 UTC, gw000 commented on backends/flask/app/__init__.py
> +    Relation = import_module("polar.data_filtering", "oso").Relation
Oh yeah, I guess you can! For some reason I though I couldn't import directly out of `polar`

2021-09-09 21:34 UTC, leina05 requested changes
The new repo looks great! The old repo needs to have the old `sqlalchemy-roles` stuff cleaned out of it, which I think you could do pretty easily using the implementation you wrote for roles in the new repo. But that can be a follow-up to this PR.

For some reason my test setup is still broken, but others were able to run them and they passed. The `flask-sqlalchemy-oso` repo tests don't pass when running against `oso/main` build because they use the old roles that have now been removed.

One other comment: 
- can we add the new backend to the top-level readme and briefly explain the difference between the two backends?

2021-09-09 21:34 UTC, leina05 commented on backends/flask-sqlalchemy/app/routes/helpers.py
> +def authorized_resource(actn: str, cls: Type[Any], **kwargs):
```suggestion
def authorized_resource(action: str, cls: Type[Any], **kwargs):
```

2021-09-09 21:34 UTC, leina05 commented on backends/flask-sqlalchemy/app/routes/helpers.py
> +    rsrcs = authorized_resources(actn, cls, **kwargs)
```suggestion
    resources = authorized_resources(action, cls, **kwargs)
```

2021-09-09 21:34 UTC, leina05 commented on backends/flask-sqlalchemy/app/routes/helpers.py
> +    return rsrcs[0]
```suggestion
    if len(resources) == 0:
        raise NotFound
    return resources[0]
```

2021-09-09 21:34 UTC, leina05 commented on backends/flask-sqlalchemy/app/routes/helpers.py
> +def authorized_resources(actn: str, cls: Type[Any], **kwargs):
expand shortened variable names

2021-09-09 21:34 UTC, leina05 commented on backends/flask-sqlalchemy/app/helpers.py
> +def assign_role(user, resource, role_name, session):
Is this used anywhere?

2021-09-09 22:20 UTC, samscott89 commented on backends/flask-sqlalchemy/app/routes/helpers.py
> +def session(func):
We should use as few of these helpers as possible, so that for someone _not_ using SQLAlchemy it's clear what work they should be doing. We should use regular sessions, and use the data filtering APIs instead.

2021-09-09 23:48 UTC, gw000 commented on backends/flask-sqlalchemy/app/helpers.py
> +def assign_role(user, resource, role_name, session):
No, it's left over from the old backend 👍

2021-09-09 23:49 UTC, gw000 commented on backends/flask-sqlalchemy/app/models.py
> +class OrgRole(Base):
They were created by `sqlalchemy-oso` when we used the built-in RBAC. In the updated `flask-sqlalchemy-oso` they are there.

2021-09-10 00:06 UTC, gw000 commented on backends/flask-sqlalchemy/app/routes/helpers.py
> +def session(func):
They're all gone 😄

2021-09-10 00:13 UTC, gw000 commented on backends/flask-sqlalchemy-oso/README.md
> +the `sqlalchemy-oso` library][docs-roles] that this app uses heavily.
👍

2021-09-10 00:13 UTC, gw000 commented on backends/flask-sqlalchemy-oso/README.md
> +[docs-roles]: https://docs.osohq.com/python/new-roles.html
✂️

2021-09-10 00:25 UTC, gw000 commented
Alright everyone thanks for the review, I think I addressed all the issues now. We'll have to update the other backends to make sure they 403 in the right places though.

2021-09-10 15:30 UTC, leina05 approved these changes
🥇

2021-09-10 16:28 UTC, merged